import { create } from 'zustand';
import type { WorkflowModel } from './useWorkflowStore';
import { validateEvaluation, type EvaluationResults } from '@/data/evaluation';

type ImportedResult = EvaluationResults;
let importRevision = 0;

type ImportState = 'idle' | 'reading' | 'validating' | 'ready' | 'invalid';

interface EvaluationStoreState {
  source: 'built_in' | 'imported';
  evaluation: EvaluationResults | null;
  generation: number;
  fileName: string | null;
  previousModel: WorkflowModel | null;
  importState: ImportState;
  errors: string[];
  importFile: (file: File, previousModel: WorkflowModel) => Promise<ImportedResult | null>;
  importText: (text: string, fileName: string, previousModel: WorkflowModel) => ImportedResult | null;
  clearError: () => void;
  closeImport: () => void;
}

function validateImportedText(text: string) {
  try {
    const data = JSON.parse(text);
    if (data.version !== 'evaluation.v1') return { value: null, errors: ['Expected an evaluation.v1 result generated by the current DGraInsight Offline Evaluator.'] };
    const result = validateEvaluation(data);
    return result.ok ? { value: result.value as ImportedResult, errors: [] as string[] } : { value: null, errors: result.errors };
  } catch { return { value: null, errors: ['Invalid JSON'] }; }
}

export const useEvaluationStore = create<EvaluationStoreState>((set, get) => ({
  source: 'built_in',
  evaluation: null,
  generation: 0,
  fileName: null,
  previousModel: null,
  importState: 'idle',
  errors: [],
  importFile: async (file, previousModel) => {
    const revision = ++importRevision;
    set({ importState: 'reading', errors: [] });
    let text: string;
    try {
      text = await file.text();
    } catch (error) {
      if (revision !== importRevision) return null;
      set({
        importState: 'invalid',
        errors: ['The selected file could not be read: ' + (error instanceof Error ? error.message : String(error))],
      });
      return null;
    }
    if (revision !== importRevision) return null;
    set({ importState: 'validating' });
    return get().importText(text, file.name, previousModel);
  },
  importText: (text, fileName, previousModel) => {
    ++importRevision;
    const result = validateImportedText(text);
    if (!result.value) {
      set({ importState: 'invalid', errors: result.errors });
      return null;
    }
    set({
      source: 'imported',
      generation: get().generation + 1,
      evaluation: result.value,
      fileName,
      previousModel: get().source === 'imported' ? get().previousModel : previousModel,
      importState: 'ready',
      errors: [],
    });
    return result.value;
  },
  clearError: () => set({ errors: [], importState: get().source === 'imported' ? 'ready' : 'idle' }),
  closeImport: () => { ++importRevision; set({
    source: 'built_in',
    evaluation: null,
    fileName: null,
    previousModel: null,
    importState: 'idle',
    errors: [],
  }); },
}));
