import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),requests=[],errors=[];
 page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.PERFORMANCE_URL||'http://127.0.0.1:5181/DGraInsight/',{waitUntil:'domcontentloaded'});
 const area=page.locator('#dgra-performance-evidence'),summary=area.locator('[data-testid="performance-summary"]');
 await area.getByRole('button').first().waitFor();assert.equal(await summary.count(),0);
 await area.getByRole('button',{name:'HUFL → MUFL',exact:true}).click();
 await summary.waitFor();assert.match(await summary.innerText(),/0.35204207/);assert.match(await summary.innerText(),/ΔMAE = after removal − baseline\. Above zero: worse; below zero: better\./);assert.match(await summary.innerText(),/MAE change \(%\)[\s\S]*MSE change \(%\)/);assert.equal(await summary.getByRole('button',{name:'By forecast step',exact:true}).getAttribute('aria-pressed'),'true');assert.equal(await summary.locator('details').getAttribute('open'),null);
 const consistency=summary.getByRole('heading',{name:/Across-sample consistency/}).locator('..').locator('..');assert.match(await consistency.innerText(),/MAE[\s\S]*improved[\s\S]*degraded[\s\S]*little change[\s\S]*MSE/);assert.match(await consistency.innerText(),/n = \d+\/40/);
 assert.doesNotMatch(await summary.innerText(),/Supported|Not supported|Detail|BH|对照均值|稳定性|显著性/);
 assert.equal(await summary.getByRole('button',{name:'Window 2',exact:true}).count(),0);
 assert.equal(await page.getByRole('button',{name:'Select window 2',exact:true}).count(),0);
 assert.deepEqual(await page.getByLabel('Graph window',{exact:true}).locator('option').allTextContents(),['Window 1']);
 await area.getByRole('button',{name:'HUFL → LUFL',exact:true}).click();
 await summary.getByRole('button',{name:'Window 2',exact:true}).click();
 await summary.waitFor();const relation=(await summary.locator('.eyebrow').first().innerText());
 assert.match(await consistency.innerText(),/HUFL → LUFL/);assert.match(await consistency.innerText(),/Single window 2[\s\S]*Selected context[\s\S]*All relevant windows/i);assert.doesNotMatch(await consistency.innerText(),/Single window 1/i);
 await summary.getByRole('button',{name:'All relevant windows',exact:true}).click();
 await summary.getByRole('button',{name:'MSE',exact:true}).click();
 assert.equal(await summary.locator('.eyebrow').first().innerText(),relation);
 await page.getByLabel('Graph sample',{exact:true}).selectOption('1');
 await page.waitForFunction(()=>!document.body.innerText.includes('Loading performance data'));
 if(await summary.count())assert.match(await summary.innerText(),/Test sample 537/);
 await page.getByLabel('Graph sample',{exact:true}).selectOption('0');
 await area.getByRole('button').first().waitFor();
 await page.getByLabel('Graph window',{exact:true}).selectOption('0');
 await page.getByRole('button',{name:'Matrix',exact:true}).click();
 await page.getByRole('gridcell',{name:/^HUFL → MUFL:/}).click();
 await summary.waitFor();assert.match(await summary.locator('.eyebrow').first().innerText(),/HUFL → MUFL/);
 assert.equal(await page.getByRole('gridcell',{name:/^HUFL → MUFL:/}).evaluate(e=>e.style.outline),'rgb(22, 130, 127) solid 2px');
 assert.equal(requests.filter(u=>u.includes('/performance/v1/dgraformer.json')).length,1);
 await page.getByRole('button',{name:'MSGNet · scale graph',exact:true}).click();
 await page.getByRole('heading',{name:/Internal scale graph/}).waitFor();
 assert.equal(requests.filter(u=>u.includes('/performance/v1/msgnet.json')).length,0);
 assert.equal(await page.getByText('Scale graph artifact',{exact:true}).count(),0);
 await page.getByRole('button',{name:'Matrix',exact:true}).click();
 await page.getByTitle(/^G4 → G3:/).click();
 const directions=page.getByRole('group',{name:'MSGNet relation direction'});await directions.waitFor();
 assert.equal(await directions.getByRole('button').count(),2);
 const msg=page.locator('#msgnet-performance-evidence [data-testid="performance-summary"]');
 await msg.waitFor();assert.match(await msg.innerText(),/G4 → G3/);
 assert.match(await msg.getByRole('heading',{name:/Across-sample consistency/}).locator('..').locator('..').innerText(),/All relevant scales[\s\S]*71\.4% improved/);
 await directions.getByRole('button',{name:/Source G3.*Target G4/}).click();
 await msg.waitFor();assert.match(await msg.innerText(),/G3 → G4/);
 await msg.getByRole('button',{name:'Scale 2',exact:true}).click();
 await page.getByRole('heading',{name:'Internal scale graph · scale_index 2',exact:true}).waitFor();
 assert.match(await msg.innerText(),/G3 → G4/);
 await page.getByLabel('MSGNet graph sample',{exact:true}).selectOption('1');
 await page.waitForFunction(()=>document.querySelector('#msgnet-performance-evidence')?.textContent.includes('Test sample 537'));
 assert.match(await msg.innerText(),/G3 → G4/);
 await msg.getByRole('button',{name:'By forecast step',exact:true}).click();
 await msg.getByLabel('Error point').selectOption('5');await msg.getByRole('status').filter({hasText:'Forecast step 6'}).waitFor();
 await msg.locator('details summary').click();assert.match(await msg.innerText(),/FAIL/);
 await msg.screenshot({path:'.tmp/performance-final.png'});
 assert.equal(requests.filter(u=>u.includes('/performance/v1/msgnet.json')).length,1);
 assert.equal(requests.filter(u=>u.includes('/data/evidence/')).length,0);
 assert.deepEqual(errors,[]);
 assert.ok(!/[\p{Script=Han}]/u.test(await page.locator('body').innerText()));
 const broken=await browser.newPage();
 await broken.route('**/performance/v1/dgraformer.json*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({version:'obsolete'})}));
 await broken.goto(process.env.PERFORMANCE_URL||'http://127.0.0.1:5181/DGraInsight/',{waitUntil:'domcontentloaded'});
 await broken.locator('#dgra-performance-evidence [role="alert"]').waitFor();
 assert.equal(await broken.locator('[data-testid="performance-summary"]').count(),0);
 console.log('Browser PASS: select-first, invalid windows omitted, sample/scope/scale sync, metrics, methods, 1 fetch/model, no audit fetch, fail-closed version.');
} finally {await browser.close();}
